// ─── RMASC FACTORY — Professional License System v2 ─────────────────────
// Self-contained license key format: GD-YYMMDD-HHHHHH
//   GD      = prefix (RMASC identifier)
//   YYMMDD  = expiry date (e.g., 270629 = 29 June 2027)
//   HHHHHH  = HMAC-SHA256 verification code (6 hex chars)
//
// The HMAC proves the key was generated by RMASC and not tampered with.
// No external payload file needed — the key is self-contained.

const crypto = require('crypto');
const fs = require('fs');
const path = require('path');
const os = require('os');

const LICENSE_SECRET = 'rmasc-license-hmac-v1-k3y!@#2026$%^';
const LICENSE_FILE = 'rmasc_license.key';

function getAppDataDir() {
  const base = process.env.APPDATA || path.join(os.homedir(), 'AppData', 'Roaming');
  const dir = path.join(base, 'RMASC-FACTORY');
  if (!fs.existsSync(dir)) { try { fs.mkdirSync(dir, { recursive: true }); } catch {} }
  return dir;
}
function getLicensePath() { return path.join(getAppDataDir(), LICENSE_FILE); }

// ═══════════════════════════════════════════════════════════════════════════
//  GENERATE LICENSE KEY
// ═══════════════════════════════════════════════════════════════════════════
// Generates: GD-YYMMDD-HHHHHH
function generateLicense({ expDays = 365 } = {}) {
  const now = new Date();
  const expiresAt = new Date(now.getTime() + expDays * 24 * 60 * 60 * 1000);
  const yy = String(expiresAt.getFullYear()).slice(2);
  const mm = String(expiresAt.getMonth() + 1).padStart(2, '0');
  const dd = String(expiresAt.getDate()).padStart(2, '0');
  const dateStr = `${yy}${mm}${dd}`;

  // Create HMAC of the date string
  const hmac = crypto.createHmac('sha256', LICENSE_SECRET)
    .update(`GD-${dateStr}`)
    .digest('hex')
    .toUpperCase()
    .slice(0, 6);

  const licenseKey = `GD-${dateStr}-${hmac}`;
  return { licenseKey, expiresAt };
}

// ═══════════════════════════════════════════════════════════════════════════
//  VALIDATE LICENSE KEY
// ═══════════════════════════════════════════════════════════════════════════
function validateLicense(licenseKey) {
  const result = {
    valid: false, expired: false, tampered: false,
    company: 'RMASC CLIENT OFFICIEL', type: 'ENTERPRISE',
    issuedAt: null, expiresAt: null,
    remainingDays: 0, error: '',
  };

  try {
    const rawKey = (licenseKey || '').trim();
    const key = rawKey.toUpperCase();

    // Format check: GD-YYMMDD-HHHHHH (uppercase)
    if (!/^GD-\d{6}-[0-9A-F]{6}$/.test(key)) {
      result.error = `Format invalide. Utilisez: GD-YYMMDD-XXXXXX (ex: GD-${String(new Date().getFullYear()).slice(2)}${String(new Date().getMonth()+1).padStart(2,'0')}${String(new Date().getDate()).padStart(2,'0')}-ABCDEF)`;
      return result;
    }

    const parts = key.split('-');
    const dateStr = parts[1]; // YYMMDD
    const providedHmac = parts[2];

    // Verify HMAC
    const expectedHmac = crypto.createHmac('sha256', LICENSE_SECRET)
      .update(`GD-${dateStr}`)
      .digest('hex')
      .toUpperCase()
      .slice(0, 6);

    if (providedHmac !== expectedHmac) {
      result.error = 'Clé de licence invalide — code de vérification incorrect.';
      result.tampered = true;
      return result;
    }

    // Parse expiry date
    const yy = parseInt(dateStr.slice(0, 2));
    const mm = parseInt(dateStr.slice(2, 4)) - 1;
    const dd = parseInt(dateStr.slice(4, 6));
    const fullYear = 2000 + yy;
    const expiresAt = new Date(fullYear, mm, dd, 23, 59, 59);

    // Check expiry
    const now = new Date();
    if (now > expiresAt) {
      result.expired = true;
      result.error = '⚠️ Licence expirée. Veuillez contacter RMASC pour le renouvellement.';
      result.expiresAt = expiresAt;
      result.remainingDays = 0;
      return result;
    }

    // Valid!
    const diffMs = expiresAt.getTime() - now.getTime();
    const remainingDays = Math.ceil(diffMs / (1000 * 60 * 60 * 24));

    result.valid = true;
    result.expiresAt = expiresAt;
    result.issuedAt = new Date();
    result.remainingDays = remainingDays;
    return result;

  } catch (err) {
    result.error = 'Erreur de validation: ' + (err.message || 'inconnue');
    result.tampered = true;
    return result;
  }
}

// ═══════════════════════════════════════════════════════════════════════════
//  FILE I/O
// ═══════════════════════════════════════════════════════════════════════════

function saveLicense(licenseKey) {
  try {
    fs.writeFileSync(getLicensePath(), licenseKey.trim(), 'utf8');
    return true;
  } catch (err) {
    console.error('[LICENSE] ❌ Failed to save license:', err.message);
    return false;
  }
}

function loadLicense() {
  try {
    if (fs.existsSync(getLicensePath())) return fs.readFileSync(getLicensePath(), 'utf8').trim();
  } catch {}
  return null;
}

function deleteLicense() {
  try { if (fs.existsSync(getLicensePath())) fs.unlinkSync(getLicensePath()); } catch {}
}

function checkLicenseStatus() {
  const storedKey = loadLicense();
  if (!storedKey) {
    return { valid: false, error: 'Aucune licence trouvée. Veuillez activer le logiciel.', company: '', type: '', remainingDays: 0, requiresActivation: true };
  }
  return { ...validateLicense(storedKey), requiresActivation: false };
}

module.exports = { generateLicense, validateLicense, saveLicense, loadLicense, deleteLicense, checkLicenseStatus, getLicensePath };
